// Auto-generated by GitHub Actions build workflow.
// Do not edit manually — BUILD_COMMIT is overwritten on each build.
namespace AIXWhatsAppLocal;

public static class BuildInfo
{
    public const string Version = "0.2.1";
    public const string Commit = "dev-local";
    public const string BuildDate = "unknown";
}